### ISSUE TITLE
Sample Email Auth Service is unable to access the user table 

### ISSUE THREAD

**Issue by moiAK** [Esri/AdoptA#97]
All three live examples fail because the email authentication GP service is unable to access the UserTable in SDE.  Below is the error detail. 

_"Error executing tool. AuthGP : The value does not exist.↵The value is empty.↵The value is empty.↵The value is empty.↵The value is empty.↵ERROR 000732: User table: Dataset C:\arcgisserver\directories\arcgissystem\arcgisinput\adoptacatchbasin.GPServer\extracted\v101\Connection to egdb.sde\egdb.DBO.UserTable does not exist or is not supported"_

**Comment by shoe913** [comment]
This appears to have been an issue with the license update. 

The licenses have been reapplied and everything appears to be working. 

Let us know if you continue to have issues.
